# Generated by Django 2.2.4 on 2020-01-25 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='produtoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo'), ('3', 'Excluido')], default=1, max_length=1)),
                ('prodserv', models.CharField(choices=[('1', 'Produto'), ('2', 'Serviço')], default=1, max_length=1)),
                ('unidade', models.CharField(choices=[('1', 'Produto'), ('2', 'Serviço')], default=1, max_length=1)),
                ('nome', models.CharField(max_length=200)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.CharField(blank=True, max_length=15, null=True)),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
