# Generated by Django 2.2.4 on 2020-01-29 03:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0002_produtomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='produtoItemModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.CharField(default=1, max_length=15)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia.produtoModel')),
            ],
        ),
        migrations.CreateModel(
            name='orcamentoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('1', 'Aberto'), ('2', 'Finalizado'), ('3', 'Cancelado')], max_length=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('obs', models.CharField(blank=True, max_length=1000, null=True)),
                ('dataFechamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia.clienteModel')),
                ('produtoItem', models.ManyToManyField(to='gerencia.produtoItemModel')),
            ],
        ),
    ]
