# Generated by Django 2.2.4 on 2020-01-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0005_produtoitemmodel_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentomodel',
            name='estado',
            field=models.CharField(choices=[('1', 'Aberto'), ('2', 'Finalizado'), ('3', 'Cancelado'), ('4', 'Descartado')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='produtoitemmodel',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtomodel',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
