# Generated by Django 2.2.4 on 2020-01-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0006_auto_20200130_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentomodel',
            name='pagamento',
            field=models.CharField(blank=True, choices=[('1', 'Dinheiro'), ('2', 'Cartão')], max_length=1, null=True),
        ),
    ]
