# Generated by Django 2.2.4 on 2020-01-30 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0007_orcamentomodel_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='caixaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operacao', models.CharField(choices=[('1', 'Entrada'), ('2', 'Saida')], default=1, max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento', models.CharField(blank=True, choices=[('1', 'Dinheiro'), ('2', 'Cartao')], max_length=1, null=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('valorOperacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
