# Generated by Django 2.2.4 on 2020-01-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0010_caixamodel_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentomodel',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentomodel',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
