# Generated by Django 2.2.4 on 2020-01-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0011_auto_20200130_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixamodel',
            name='referencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
