# Generated by Django 2.2.4 on 2020-02-14 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0012_auto_20200131_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='subProdutoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo'), ('3', 'Excluido')], default=1, max_length=1)),
                ('nome', models.CharField(max_length=200)),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
