# Generated by Django 2.2.4 on 2020-02-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0013_subprodutomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtomodel',
            name='subProduto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gerencia.subProdutoModel'),
            preserve_default=False,
        ),
    ]
