# Generated by Django 2.2.4 on 2020-02-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0015_auto_20200214_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentomodel',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
